dev:
  mysql:
    username: root
    password: 123456
    host: 10.66.210.220
    port: 3306
    database: iwhite

prod:
  mysql:
    username: prod_user
    password: prod_password
    host: db.example.com
    port: 3306
    database: prod_db
